export const GENERAL_FACTOR = 10; // 1- NORMAL, 10-ACELERADO PARA PRUEBAS

export const PRODUCTION_INCREMENT = 1;
export const BUILD_COST_INCREMENT = 1.5;
export const RESEARCH_COST_INCREMENT = 1.5;
export const BUILD_TIME_INCREMENT = 1.5;
export const RESEARCH_TIME_INCREMENT = 1.5;
