export const GENERAL_FACTOR = 1; // 1- NORMAL, 10-ACELERADO PARA PRUEBAS

export const PRODUCTION_INCREMENT = 1.3;
export const BUILD_COST_INCREMENT = 1.3;
export const RESEARCH_COST_INCREMENT = 1.8;
export const BUILD_TIME_INCREMENT = 1.8;
export const RESEARCH_TIME_INCREMENT = 1.7;
